apiVersion: v1
kind: Service
metadata:
  name: ml-dashboard-frontend
spec:
  selector:
    app: ml-dashboard-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
